### ISSUE TITLE
tracking issue for tech plan

### ISSUE THREAD

**Issue by zakarumych** [SPbPU-Rust/secret-santa-service#1]
Список необходимых фичией из ТЗ

- [ ] При подключении к сервису пользователь использует имя. Аутентификация не требуется.
- [ ] Пользователи могут создавать группы.
- [ ] Пользователи могут присоединяться к группам.
- [ ] Пользователи могут иметь права администратора в группе.
- [ ] Пользователь создавший группу автоматически становится администратором.
- [ ] Администратор может назначить другого пользователя в группе администратором.
- [ ] Администратор может снять с себя полномочия администратора, если в группе есть хотя бы еще 1 администратор.
- [ ] Администратор может покинуть группу только есть в группе есть хотя бы еще 1 администратор.
- [ ] Администратор может удалить группу.
- [ ] Администратор может дать команду и сервис назначит секретного Санту для каждого члена группы, выбирая из остальных членов группы.
- [ ] Каждый член группы будет назначен секретным Сантой строго одному другому члену группы.
- [ ] После этого группа становится закрытой, в нее нельзя войти или выйти.
- [ ] Пользователи могут запросить, для кого в группе они стали секретным Сантой.
- [ ] Использовать БД для хранения данных о пользователях, группах и секретных Сантах. Но можно обойтись хранением данных в памяти.
- [ ] Работает через HTTP REST с JSON сообщениями.
- [ ] Утилита для общения с сервисом.

**Comment by alekseevad** [comment]
@zakarumych  а консольное приложение только под линукс подразумевается?

**Comment by zakarumych** [comment]
Под хотя бы одну любую платформу
